version: "3"
services:
  nodejs-bookshelf-app-lb:
    build: ./nginx
    ports: 
      - 4000:80
    depends_on:
      - nodejs-bookshelf-app-prod
    links:
      - nodejs-bookshelf-app-prod
  nodejs-bookshelf-app-prod:
    build: .
    environment:
      - NODE_ENV=production
      - MYSQL_DATABASE=bookshelf
      - MYSQL_USER=librarian
      - MYSQL_PASSWORD=secret
    depends_on:
      - nodejs-bookshelf-db-prod
  nodejs-bookshelf-db-prod:
    image: mysql:5.5
    environment:
      - MYSQL_DATABASE=bookshelf
      - MYSQL_USER=librarian
      - MYSQL_PASSWORD=secret
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
